# Site settings
title: hello
header-img: img/home-bg.png
email: krishel.lasam@gmail.com
copyright_name: krishl
description: > # this means to ignore newlines until "baseurl:"
  coding life
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  krishl
learn_profile: krishl
email_username: krishel.lasam@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
